version: "3.1"

networks:
  stack_ponte:
    external: true

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "807:80"
    environment:
      WORDPRESS_DB_HOST: ${DATABASE}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: wordubyus
    volumes:
      - ${PATHPESSOAL}/wordubyus:/var/www/html
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.wordubyus.rule=Host(`wordubyus.${DOMAIN}`)
      - traefik.http.services.wordubyus.loadbalancer.server.port=80
